services:
  postgres-auth:
    image: postgres:16
    container_name: postgres_auth
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_auth:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  postgres-event:
    image: postgres:16
    container_name: postgres_event
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: event_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_event:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d event_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./backend/auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    environment:
      DB_HOST: postgres-auth
      DB_PORT: 5432
      DB_NAME: auth_db
      DB_USER: admin
      DB_PASSWORD: admin
      PYTHONPATH: /main
    depends_on:
      postgres-auth:
        condition: service_healthy
    ports:
      - "8000:8000"
  event-service:
    build:
      context: ./backend/events_service
      dockerfile: Dockerfile
    container_name: event_service
    environment:
      DB_HOST: postgres-event
      DB_PORT: 5432
      DB_NAME: event_db
      DB_USER: admin
      DB_PASSWORD: admin
      PYTHONPATH: /main
    depends_on:
      postgres-event:
        condition: service_healthy
    ports:
      - "8001:8001"

volumes:
  pgdata_auth:
  pgdata_event: