services:
  gateway:
    image: nginx:latest
    container_name: api_gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - backend-network
    depends_on:
      - auth-service
      - event-service

  postgres-auth:
    image: postgres:16
    container_name: postgres_auth
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_auth:/var/lib/postgresql/data
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-event:
    image: postgres:16
    container_name: postgres_event
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: event_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_event:/var/lib/postgresql/data
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d event_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-attendance:
    image: postgres:16
    container_name: postgres_attendance
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: attendance_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata_attendance:/var/lib/postgresql/data
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d attendance_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio:latest
    container_name: event_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - ./minio_data:/data
    networks:
      - backend-network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD-SHELL", "mc ready local"]
      interval: 10s
      timeout: 5s
      retries: 3

  auth-service:
    build:
      context: ./backend/auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    environment:
      DB_HOST: postgres-auth
      DB_PORT: 5432
      DB_NAME: auth_db
      DB_USER: admin
      DB_PASSWORD: admin
      PYTHONPATH: /main
    networks:
      - backend-network
    depends_on:
      postgres-auth:
        condition: service_healthy
    ports:
      - "8000:8000"

  event-service:
    build:
      context: ./backend/events_service
      dockerfile: Dockerfile
    container_name: event_service
    environment:
      DB_HOST: postgres-event
      DB_PORT: 5432
      DB_NAME: event_db
      DB_USER: admin
      DB_PASSWORD: admin
      MINIO_ENDPOINT: http://minio:9000
      MINIO_BUCKET: events-photos
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password123
      PYTHONPATH: /main
    networks:
      - backend-network
    depends_on:
      postgres-event:
        condition: service_healthy
      minio:
        condition: service_healthy
    ports:
      - "8001:8001"

  attendance-service:
    build:
      context: ./backend/attendance_service
      dockerfile: Dockerfile
    container_name: attendance_service
    environment:
      DB_HOST: postgres-attendance
      DB_PORT: 5432
      DB_NAME: attendance_db
      DB_USER: admin
      DB_PASSWORD: admin
      PYTHONPATH: /main
    networks:
      - backend-network
    depends_on:
      postgres-attendance:
        condition: service_healthy
    ports:
      - "8002:8002"

  web-app:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    container_name: web_app
    volumes:
      - ./frontend/web:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - backend-network
    depends_on:
      - event-service
      - auth-service
    ports:
      - "3000:5173"

networks:
  backend-network:
    driver: bridge

volumes:
  pgdata_auth:
  pgdata_event:
  pgdata_attendance: